In [1]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
import sympy as sy

# Q1

In [2]:
A = np.arange(1,10,1).reshape(3,3)
B = np.arange(10,19,1).reshape(3,3)

A_B = np.matmul(A,B)
B_A = np.matmul(B,A)

print("A.B = \n", A_B)
print("B.A = \n", B_A)

A.B = 
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]
B.A = 
 [[138 171 204]
 [174 216 258]
 [210 261 312]]


# Q2

In [3]:
M = np.array([[4,5,-5],[-1,3,-1],[7,1,1]])
MT = M.T
MS = (M + MT) / 2
MW = (M - MT) / 2

print("M.T is \n", MT)
print("Symmetric part of M is: \n", MS)
print("Skew-symmetric part of M is: \n", MW)

M.T is 
 [[ 4 -1  7]
 [ 5  3  1]
 [-5 -1  1]]
Symmetric part of M is: 
 [[4. 2. 1.]
 [2. 3. 0.]
 [1. 0. 1.]]
Skew-symmetric part of M is: 
 [[ 0.  3. -6.]
 [-3.  0. -1.]
 [ 6.  1.  0.]]


# Q3

In [4]:
AS = (A + A.T) / 2
BW = (B - B.T) / 2

AS_BW = np.matmul(AS, BW)
TR_AS_BW = np.trace(AS_BW)
print("Trace of A_s.B_w is: ", TR_AS_BW)

Trace of A_s.B_w is:  0.0


# Q4

In [5]:
t_sy = sy.symbols('t')
omega_sy = sy.symbols('omega')
A_sy = sy.Matrix([[t_sy, t_sy**2, sy.sin(omega_sy * t_sy)], 
                  [sy.cosh(t_sy), sy.log(t_sy), 17 * t_sy], 
                  [1 / t_sy, 1 / (t_sy**2), sy.log(t_sy**2)]])
der_A = A_sy.diff(t_sy)
print('Derivative of A(t)')
display(der_A)

Derivative of A(t)


Matrix([
[      1,     2*t, omega*cos(omega*t)],
[sinh(t),     1/t,                 17],
[-1/t**2, -2/t**3,                2/t]])

# Q5

In [10]:
G = np.array([[10, 50, -50], [50, 100, 10], [-50, 10, 100]])
eigvals_G, eigvecs_G = np.linalg.eig(G)
# print('Eigenvalues of G')
# print(eigvals_G)
# print('Eigenvectors of G')
# print(eigvecs_G)

eigvals_G_inds = np.argsort(eigvals_G, )[::-1]
eigvals_G_sorted = eigvals_G[eigvals_G_inds]
eigvecs_G_sorted = eigvecs_G[:,eigvals_G_inds]

print('Sorted eigenvalues of G:')
print(eigvals_G_sorted)
print('Sorted eigenvectors of G')
print(eigvecs_G_sorted)

print(f"{chr(955)}_1 is {eigvals_G_sorted[0]} with v_1 {eigvecs_G_sorted[:,0]}")
print(f"{chr(955)}_2 is {eigvals_G_sorted[1]} with v_2 {eigvecs_G_sorted[:,1]}")
print(f"{chr(955)}_3 is {eigvals_G_sorted[2]} with v_3 {eigvecs_G_sorted[:,2]}")



Sorted eigenvalues of G:
[131.24038405 110.         -31.24038405]
Sorted eigenvectors of G
[[ 0.50380256  0.         -0.86381884]
 [ 0.61081216  0.70710678  0.35624221]
 [-0.61081216  0.70710678 -0.35624221]]
λ_1 is 131.24038404635962 with v_1 [ 0.50380256  0.61081216 -0.61081216]
λ_2 is 110.0 with v_2 [0.         0.70710678 0.70710678]
λ_3 is -31.240384046359594 with v_3 [-0.86381884  0.35624221 -0.35624221]


# Q6

In [22]:
G_inv = np.linalg.inv(G)
print(f"G inverse is: \n {G_inv}")
eigvals_G_inv, eigvecs_G_inv = np.linalg.eig(G_inv)

eigval_G_inv_sorted_inds = np.argsort(eigvals_G_inv)[::-1]
eigvals_G_inv_sorted = eigvals_G_inv[eigval_G_inv_sorted_inds]
eigvecs_G_inv_sorted = eigvecs_G_inv[:,eigval_G_inv_sorted_inds]

print('Eigenvalues of G inverse')
print(f"{chr(955)}_1 is {eigvals_G_inv_sorted[0]} with v_1 {eigvecs_G_inv_sorted[:,0]}")
print(f"{chr(955)}_2 is {eigvals_G_inv_sorted[1]} with v_2 {eigvecs_G_inv_sorted[:,1]}")
print(f"{chr(955)}_3 is {eigvals_G_inv_sorted[2]} with v_3 {eigvecs_G_inv_sorted[:,2]}")

inverse_eigvals_G = np.sort(1 / eigvals_G_sorted)[::-1]
print('Inverse of the eigenvalues of G')
print(inverse_eigvals_G)

if np.isclose(eigvals_G_inv_sorted, inverse_eigvals_G, atol=1e-5).all:
    print('The eigenvalues of the inverse matrix are the inverses of the eigenvalues of the original matrix')

G inverse is: 
 [[-0.02195122  0.01219512 -0.01219512]
 [ 0.01219512  0.00332594  0.00576497]
 [-0.01219512  0.00576497  0.00332594]]
Eigenvalues of G inverse
λ_1 is 0.00909090909090909 with v_1 [0.         0.70710678 0.70710678]
λ_2 is 0.007619605864965757 with v_2 [ 0.50380256  0.61081216 -0.61081216]
λ_3 is -0.032009849767404785 with v_3 [-0.86381884  0.35624221 -0.35624221]
Inverse of the eigenvalues of G
[ 0.00909091  0.00761961 -0.03200985]
The eigenvalues of the inverse matrix are the inverses of the eigenvalues of the original matrix


# Q7

In [50]:
T = np.array([[1, 0, 0], [0, 11/4, -np.sqrt(3)/4], [0, -np.sqrt(3)/4, 9/4]])
print('T')
print(T)
eigvals_T, eigvecs_T = np.linalg.eig(T)

sorted_inds_eigvals_T = np.argsort(eigvals_T)[::-1]
sorted_eigvals_T = eigvals_T[sorted_inds_eigvals_T]
sorted_eigvecs_T = eigvecs_T[:,sorted_inds_eigvals_T]

print(f"Sorted eigenvalues of T are: \n {sorted_eigvals_T}")
print(f"Sorted eigenvectors of T are: \n {sorted_eigvecs_T}")


# The angle between the first eigenvector and the x1 axis
first_eigvec = sorted_eigvecs_T[:, 0]
lambda_1 = sorted_eigvals_T[0]
magnitude = np.linalg.norm(first_eigvec)
angle = np.arccos(first_eigvec[0]) # Angle in radians
angle_degrees = np.degrees(angle)
print(f" b) Angle between the first eigenvector and the x1-axis: {angle:.4f} radians ({angle_degrees:.4f} degrees)")

T
[[ 1.         0.         0.       ]
 [ 0.         2.75      -0.4330127]
 [ 0.        -0.4330127  2.25     ]]
Sorted eigenvalues of T are: 
 [3. 2. 1.]
Sorted eigenvectors of T are: 
 [[ 0.         0.         1.       ]
 [-0.8660254 -0.5        0.       ]
 [ 0.5       -0.8660254  0.       ]]
 b) Angle between the first eigenvector and the x1-axis: 1.5708 radians (90.0000 degrees)
