In [1]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

# Q1

In [9]:
A = np.arange(1,10,1).reshape(3,3)
B = np.arange(10,19,1).reshape(3,3)

A_B = np.dot(A,B)
B_A = np.dot(B,A)

print("A.B = \n", A_B)
print("B.A = \n", B_A)

A.B = 
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]
B.A = 
 [[138 171 204]
 [174 216 258]
 [210 261 312]]


# Q2

In [16]:
M = np.array([[4,5,-5],[-1,3,-1],[7,1,1]])
MT = M.T
S = (M + MT) / 2
skew = (M - MT) / 2

print("M.T is \n", MT)
print("Symmetric part of M is \n", S)
print("Skew-symmetric part of M is \n", skew)

M.T is 
 [[ 4 -1  7]
 [ 5  3  1]
 [-5 -1  1]]
Symmetric part of M is 
 [[4. 2. 1.]
 [2. 3. 0.]
 [1. 0. 1.]]
Skew-symmetric part of M is 
 [[ 0.  3. -6.]
 [-3.  0. -1.]
 [ 6.  1.  0.]]


# Q3

In [15]:
S

array([[4., 2., 1.],
       [2., 3., 0.],
       [1., 0., 1.]])

In [7]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
B

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])